(load "../src/init.lisp")

; error routine
(define report (lambda (what) (begin (write "FAILED " what "\n") (quit))))

(if (null? ()) 'OK (report 'null?))
(if (number? 1) 'OK (report 'number?))
(if (symbol? 'a) 'OK (report 'symbol?))
(if (string? "a") 'OK (report 'string?))
(if (pair? '(1 . 2)) 'OK (report 'pair?))
(if (list? ()) 'OK (report 'list?))
(if (list? '(1 2)) 'OK (report 'list?))
(if (equal? () ()) 'OK (report 'equal?))
(if (equal? 1 1) 'OK (report 'equal?))
(if (equal? 'a 'a) 'OK (report 'equal?))
(if (equal? "a" "a") 'OK (report 'equal?))
(if (equal? '(1 2) '(1 2)) 'OK (report 'equal?))
(if (eq? (abs 1) 1) 'OK (report 'abs))
(if (eq? (abs -1) 1) 'OK (report 'abs))
(if (eq? (frac 1.5) .5) 'OK (report 'frac))
(if (eq? (frac -1.5) -.5) 'OK (report 'frac))
(if (eq? (int 1.5) 1) 'OK (report 'int))
(if (eq? (int -1.5) -1) 'OK (report 'int))
(if (eq? (floor 1.5) 1) 'OK (report 'floor))
(if (eq? (floor -1.5) -2) 'OK (report 'floor))
(if (eq? (ceiling 1.5) 2) 'OK (report 'ceiling))
(if (eq? (ceiling -1.5) -1) 'OK (report 'ceiling))
(if (eq? (round 1.5) 2) 'OK (report 'round))
(if (eq? (round -1.5) -2) 'OK (report 'round))
(if (eq? (mod 3 2) 1) 'OK (report 'mod))
(if (eq? (gcd 1776 42) 6) 'OK (report 'gcd))
(if (even? 42) 'OK (report 'even?))
(if (odd? 41) 'OK (report 'odd?))
(if (eq? (length ()) 0) 'OK (report 'length))
(if (eq? (length '(1 2)) 2) 'OK (report 'length))
(if (equal? (append '(1 2) '(3 4)) '(1 2 3 4)) 'OK (report 'append))
(if (equal? (nthcdr '(1 2 3 4) 2) '(3 4)) 'OK (report 'nthcdr))
(if (equal? (nth '(1 2 3 4) 2) 3) 'OK (report 'nth))
(if (equal? (reverse '(1 2 3 4)) '(4 3 2 1)) 'OK (report 'reverse))
(if (equal? (member 3 '(1 2 3 4)) '(3 4)) 'OK (report 'member))
(if (eq? (foldr - 0 '(1 2 3 4)) -2) 'OK (report 'foldr))
(if (eq? (foldl - 0 '(1 2 3 4)) 2) 'OK (report 'foldl))
(if (eq? (min 1 2 3 4) 1) 'OK (report 'min))
(if (eq? (max 1 2 3 4) 4) 'OK (report 'max))
(if (equal? (filter odd? '(1 2 3 4)) '(1 3)) 'OK (report 'filter))
(if (all? odd? '(1 3)) 'OK (report 'all?))
(if (any? odd? '(1 2 3 4)) 'OK (report 'any?))
(if (equal? (mapcar odd? '(1 2 3 4)) '(#t () #t ())) 'OK (report 'mapcar))
(if (equal? (map + '(1 2) '(3 4)) '(4 6)) 'OK (report 'map))
(if (equal? (zip '(1 2) '(3 4)) '((1 3) (2 4))) 'OK (report 'zip))
(if (equal? (seq 0 4) '(0 1 2 3)) 'OK (report 'seq))
(if (equal? (seqby 4 0 -1) '(4 3 2 1)) 'OK (report 'seqby))
(if (equal? (range 1 4) '(1 2 3)) 'OK (report 'range))
(if (equal? (range 1 4 2) '(1 3)) 'OK (report 'range))
(if (eq? ((curry + 1) 2 3) 6) 'OK (report 'curry))
(if (eq? ((compose car cdr) '(1 2)) 2) 'OK (report 'compose))
(if (eq? ((Y (lambda (f) (lambda (k) (if (< 1 k) (* k (f (- k 1))) 1)))) 5) 120) 'OK (report 'Y))

(load "../examples/case.lisp")

(if (eq? (case 2 (1 'a) (2 'b) (3 'c)) 'b) 'OK (report 'case))

(load "../examples/dolist.lisp")

(define sum 0)
(dolist (x (seq 1 4)) (setq sum (+ sum x)))
(if (eq? sum 6) 'OK (report 'dolist))

(load "../examples/when.lisp")

(if (eq? (when (< 0 0) 1 2) ()) 'OK (report 'when))
(if (eq? (when (< 0 1) 1 2) 2) 'OK (report 'when))

(load "../examples/unless.lisp")

(if (eq? (unless (< 0 0) 1 2) 2) 'OK (report 'unless))
(if (eq? (unless (< 0 1) 1 2) ()) 'OK (report 'unless))

(write "Running nqueens test, this can take a long time with DEBUG...\n")
(load "../examples/nqueens.lisp")

(write "SUCCESS\n")
(quit)
